title: Kevin Madura
baseurl: /
permalink: /:title
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima

# Exclude these files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .git/
  - .gitignore
  - .DS_Store
  - Icon?
  - "Icon\r"
  - .VolumeIcon.icns
